# ============================================================
# CONEXIÓN A LA BASE DE DATOS DE PUNTADA CREATIVA
# ============================================================
# Se fuerza el uso de SSL y el intercambio seguro de claves públicas
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_web?serverTimezone=UTC&useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0001

# Controladores JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ============================================================
# 'update' sincroniza tus clases Java automáticamente con las tablas de MySQL
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de comandos las consultas SQL ejecutadas en tiempo real
spring.jpa.show-sql=true


# Configura el dialecto de Hibernate para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configura el formato de las consultas SQL para que sean más legibles
spring.jpa.properties.hibernate.format_sql=true