wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
mvn clean install -Dspring.datasource.url="jdbc:mysql://localhost:3306/proyecto_web" -Dspring.datasource.username="root" -Dspring.datasource.password="TU_CONTRASEÑA" -Dspring.jpa.properties.hibernate.dialect="org.hibernate.dialect.MySQLDialect"
